use std::env;
use std::path::PathBuf;

fn main() {
    // tell cargo to tell rustc to link the libmpsse shared library
    println!("cargo:rustc-link-lib=mpsse");
    // tell libmpsse header file to bindgen
    let bindings = bindgen::Builder::default()
        .header("wrapper.h")
        .generate()
        .expect("Unable to generate bindings!");
    // output file generated by bindgen
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("mpsse.rs"))
        .expect("Couldn't write bindings!");
}

